### ISSUE TITLE
What happened to ipython's `%cpaste` ?

### ISSUE THREAD

**Issue by lgautier** [jupyter/jupyter_console#20]
I am getting:
```
ERROR: Line magic function `%cpaste` not found.
```

**Comment by minrk** [comment]
%cpaste doesn't work when IPython is running as a kernel for Jupyter, it only works when the IPython process has control over the input method.

I suppose a version could be implemented in the kernel by way of raw_input, though.

**Comment by lgautier** [comment]
Just to clarify (and possibly correct) my understanding: is `jupyter console` is a replacement for `ipython` ?

**Comment by minrk** [comment]
@lgautier no, `jupyter console` is the new name for the deprecated `ipython console`, which is *not* `ipython`. `console` uses the zmq kernel model that's now part of Jupyter. `ipython` isn't going away.

**Comment by takluyver** [comment]
Closing this because the new prompt_toolkit interface can do multiline paste without messing up indentation, so it reduces the need for special mechanisms to paste stuff.

**Comment by joeeoj** [comment]
So the _solution_ is to install ptpython? Definitely still very confused on why %cpaste don't exist in jupyter. I used %paste all the time in ipython consoles and it worked great.

**Comment by takluyver** [comment]
No, there isn't really a *solution* at the moment. paste/cpaste aren't in the kernel because the frontend people use most often, the notebook, has no use for them. They're only needed in terminal interfaces because of the limitations of our current terminal interfaces, but those limitations are going away in jupyter_console 5.0 (you can already try it in master). So it's unlikely that the paste/cpaste magics will be exposed in the kernel now.

**Comment by joeeoj** [comment]
Thanks for the response and sorry for the snarky comment. I guess I was just frustrated because I came to very much rely on the ipython console %paste functionality for my "test something quickly" workflow. Not only was it annoying to not have that expected functionality anymore but also have hard time finding any information online as to why it wasn't ported over.

I didn't realize there was a fix in console 5.0 to allow normal paste into the console. I just tried out by the way and it worked great. Thank you for your contributions and sorry about the sass.

**Comment by takluyver** [comment]
No problem, by internet standards that wasn't very snarky at all ;-).

To clarify something else, if `ipython` in the terminal works nicely for you, there's no need to move to `jupyter console` - we're still supporting and improving the single process IPython terminal interface. IPython has split into the language agnostic parts called Jupyter (messaging protocol, frontends, notebooks...) and the interactive Python tools which remain as IPython.

**Comment by omarfaruk2021** [comment]
UsageError: Line magic function `%paste` not found.

I found this error in the jupyter notebook kernel, what is the solution?
