### ISSUE TITLE
console does not display text/plain alternative for display_data?

### ISSUE THREAD

**Issue by janschulz** [jupyter/jupyter_console#71]
The R kernel sends plots via display_data messages and includes a text/plain representation in the message bundle. Unfortunately, it seems that the console does not display the text/plain message:

```
[ipython-notebook] λ jupyter console --kernel=ir32
Jupyter Console 4.0.3

[ZMQTerminalIPythonApp] Loading IPython extension: storemagic

In [1]: plot(1:10)

In [2]:
```

The message bundle looks like this:
```
List of 3
 $ text/plain   : chr "plot without title"
 $ image/png    : raw [1:12628] 89 50 4e 47 ...
 $ image/svg+xml: chr "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlin"| __truncated__
```

This is https://github.com/IRkernel/IRkernel/issues/262

**Comment by janschulz** [comment]
This also looks wrong:

```
[ZMQTerminalIPythonApp] Loading IPython extension: storemagic
```

**Comment by takluyver** [comment]
It looks like it works with the execute_result message (that generates an `Out` prompt), but not with display_data:

```
In [1]: class A():
      :     def _repr_png_(self):
      :         return b'oijoij'
      :     

In [2]: a= A()

In [3]: a
Out[3]: <__main__.A at 0x7f052871f1d0>

In [4]: from IPython.display import display

In [5]: display(a)
```

**Comment by flying-sheep** [comment]
well **I** was against changing it :wink:

**Comment by flying-sheep** [comment]
well, the cause is easy to identify:

1. [`handle_rich_data`](https://github.com/jupyter/jupyter_console/blob/3d24dcc14989778586b807d43314d098f30f3cc0/jupyter_console/ptshell.py#L676) is called, which in turn calls `handle_image` and then returns `True`. when returning True, `text/plain` isn’t used.
2. [`handle_image_PIL`](https://github.com/jupyter/jupyter_console/blob/3d24dcc14989778586b807d43314d098f30f3cc0/jupyter_console/ptshell.py#L721-L722) checks if the mimetype is PNG or SVG and returns if not, without doing anything.

we should make `handle_image` return True/False depending on if its delegated function can handle it the format.

AGAIN a bug exposed by having SVG! this is so useful!

**Comment by takluyver** [comment]
Thanks, well worked out. I've just opened #77 for it, and then noticed that you've done a fix as well. You've opened a PR against your own fork of the repo, though ;-)

**Comment by flying-sheep** [comment]
whoops

**Comment by janschulz** [comment]
> AGAIN a bug exposed by having SVG! this is so useful!

More "(ab)using users as guinea pigs"... :-)
